---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	cache = TRUE,
	fig.align = "center",
	warning = FALSE,
	out.width = "70%",
	tidy = TRUE,
	tidy.opts = list(width.cutoff = 60)
)
library(knitr)
library(maptools)
library(spatstat)
```


```{r BASE TOOLS, warning=FALSE}
rm(list=ls())

mu = 0.7
beta = 2.5
gamma = 5

T = function(vector){
  x=vector[1]
  y=vector[2]
  z=vector[3]
  temp=c( mu*x*(1-x-y-z),
          beta*y*(x-z),
          gamma*y*z)
  if(temp[1]<0)
    temp[1]=0
  if(temp[2]<0)
    temp[2]=0
  if(temp[3]<0)
    temp[3]=0
  return(temp)
}


N=2000
valori.x = (1:N)/N
valori.y = valori.x

num_iterazioni=20
```

Plot population behavior
```{R }
mu=3
beta=4.5


series=matrix(data=c(0.25, 0.39, 0), nrow = 1) 

for (n in 1:num_iterazioni) {
  series=rbind(series, T(series[n,]))
  if( sum(series[n+1,])==0 )
    break
}

plot(1:length(series[,1]), series[,1], ylim=c(0,1), col="blue", type="b", xlab="iteration", ylab="density", lwd=2)
lines(1:length(series[,2]), series[,2], ylim=c(0,1), col="orange", type="b", lwd=2)
lines(1:length(series[,3]), series[,3], ylim=c(0,1), col="green", type="b", lwd=2)
legend("topleft", legend = c("x", "y", "z"), col=c("blue", "orange", "green"), lwd=2)

```


Plot population behavior
```{r}
mu=3
beta=4.5

grid.1 = matrix(NA, N, N)
for (i in 1:N) {
  for (j in 1:(N+1-i)) {
    series=c(i/N, j/N, 0)

    for (n in 1:num_iterazioni) {
      series=T(series)
      if( is.outside(series) ){
        break
      }
    }
    grid.1[i,j]=n
  }
}
```

```{r}
grafico<-im(t(grid.1),valori.x,valori.y)
par(mar=c(0,0,2,0))
plot(grafico,axis=T, main=paste("mu=",mu, " and beta=", beta, sep=""))
```

Plot population behavior
```{R}
mu=3.5
beta=4.5

grid.2 = matrix(NA, N, N)
for (i in 1:N) {
  for (j in 1:(N+1-i)) {
    series=c(i/N, j/N, 0)    # x=i/N, y=j/N

    for (n in 1:num_iterazioni) {
      series=T(series)
      if( is.outside(series) ){
        break
      }
    }
    grid.2[i,j]=n
  }
}
```

```{r}
grafico<-im(t(grid.2),valori.x,valori.y)
par(mar=c(0,0,2,0))
plot(grafico,axis=T, main=paste("mu=",mu, " and beta=", beta, sep=""))
```

Plot population behavior
```{R}
mu=2.5
beta=5

grid.3 = matrix(NA, N, N)
for (i in 1:N) {
  for (j in 1:(N+1-i)) {
    series=c(i/N, j/N, 0)    # x=i/N, y=j/N

    for (n in 1:num_iterazioni) {
      series=T(series)
      if( is.outside(series) ){
        break
      }
    }
    grid.3[i,j]=n
  }
}
```

```{r}
grafico<-im(mat = t(grid.3),xcol = valori.x, yrow = valori.y)
par(mar=c(0,0,2,0))
plot(grafico,axis=T, main=paste("mu=",mu, " and beta=", beta, sep=""))
```

```{r}
save.image(".RData")
```

```{r}
mu=0.7
beta=4.5

grid.1 = matrix(NA, N, N)
for (i in 1:N) {
  for (j in 1:(N+1-i)) {
    series=c(i/N, j/N, 0)

    for (n in 1:num_iterazioni) {
      series=T(series)
      if( is.outside(series) ){
        break
      }
    }
    grid.1[i,j]=n
  }
}
```

```{r}
grafico<-im(t(grid.1),valori.x,valori.y)
par(mar=c(0,0,2,0))
plot(grafico,axis=T, main=paste("mu=",mu, " and beta=", beta, sep=""))
```






Plot population behavior
```{R }
mu=3
beta=4.5


series=matrix(data=c(0.25, 0.39, 0.2), nrow = 1) 

for (n in 1:num_iterazioni) {
  series=rbind(series, T(series[n,]))
  if( sum(series[n+1,])==0 )
    break
}

plot(1:length(series[,1]), series[,1], ylim=c(0,1), col="blue", type="b", xlab="iteration", ylab="density", lwd=2)
lines(1:length(series[,2]), series[,2], ylim=c(0,1), col="orange", type="b", lwd=2)
lines(1:length(series[,3]), series[,3], ylim=c(0,1), col="green", type="b", lwd=2)
legend("topleft", legend = c("x", "y", "z"), col=c("blue", "orange", "green"), lwd=2)

```

Plot population behavior
```{R }
mu=0.6
beta=4
gamma=6

series=matrix(data=c(0.25, 0.39, 0.01), nrow = 1) 

for (n in 1:num_iterazioni) {
  series=rbind(series, T(series[n,]))
  if( sum(series[n+1,])==0 )
    break
}

plot(1:length(series[,1]), series[,1], ylim=c(0,0.6), col="blue", type="b", xlab="iteration", ylab="density", lwd=2, xlim=c(1,6))
lines(1:length(series[,2]), series[,2], ylim=c(0,1), col="orange", type="b", lwd=2)
lines(1:length(series[,3]), series[,3], ylim=c(0,1), col="green", type="b", lwd=2)
legend("topleft", legend = c("x", "y", "z"), col=c("blue", "orange", "green"), lwd=2)

```