---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	cache = TRUE,
	fig.align = "center",
	warning = FALSE,
	out.width = "70%",
	tidy = TRUE,
	tidy.opts = list(width.cutoff = 60)
)
library(knitr)
```

```{r}
T = function(vector){
  x=vector[1]
  y=vector[2]
  z=vector[3]
  temp=c( mu*x*(1-x-y-z),
          beta*y*(x-z),
          gamma*y*z)
  for(i in 1:3){
    if(temp[i]<0)
      temp[i]=0
  }
  if(x+y+z>1)
    temp[1]=0
  return(temp)
}
```

gamma=5.1
```{r}
mu=2.1
beta=3.36

gamma=5.2

xyz = c(0.2, 0.25, 0.05)
X01 = xyz[1]
Y01 = xyz[2]
Z01 = xyz[3]

iterazioni=1e4
for(i in 1:iterazioni){
  xyz=T(xyz)
  X01 = c(X01, xyz[1])
  Y01 = c(Y01, xyz[2])
  Z01 = c(Z01, xyz[3])
}

par(pty="s", mar=c(4,0,2.4,0))
plot(X01, Y01, pch=".", asp=1, type="l", col="red", xlab = "x", ylab="y", ylim=c(0, 0.3), main = paste("gamma = ", gamma, sep=""))

xyz = c(0.1, 0.02, 0.03)
X01 = xyz[1]
Y01 = xyz[2]
Z01 = xyz[3]

for(i in 1:iterazioni){
  xyz=T(xyz)
  X01 = c(X01, xyz[1])
  Y01 = c(Y01, xyz[2])
  Z01 = c(Z01, xyz[3])
}

lines(X01, Y01, pch=".", asp=1, type="l")

points( (mu-1)/mu,0, col="orange",pch=19)
points( 1/beta, 1-1/mu-1/beta, col="green",pch=19)
points( (1-1/mu+1/beta-1/gamma), 1/gamma, col="blue",pch=19)
```


gamma=6
```{r}
mu=2.1
beta=3.36

gamma=6

xyz = c(0.2, 0.25, 0.05)
X02 = xyz[1]
Y02 = xyz[2]
Z02 = xyz[3]

iterazioni=1e4
for(i in 1:iterazioni){
  xyz=T(xyz)
  X02 = c(X02, xyz[1])
  Y02 = c(Y02, xyz[2])
  Z02 = c(Z02, xyz[3])
}

par(pty="s", mar=c(4,0,2.4,0))
plot(X02, Y02, pch=".", asp=1, xlab = "x", ylab="y", ylim=c(0, 0.3), main = paste("gamma = ", gamma, sep=""))
points( (mu-1)/mu,0, col="orange",pch=19)
points( 1/beta, 1-1/mu-1/beta, col="green",pch=19)
points( (1-1/mu+1/beta-1/gamma)/2, 1/gamma, col="blue",pch=19)
```

gamma=7
```{r}
mu=2.1
beta=3.36

gamma=7

xyz = c(0.2, 0.25, 0.05)
X03 = xyz[1]
Y03 = xyz[2]
Z03 = xyz[3]

iterazioni=1e4
for(i in 1:iterazioni){
  xyz=T(xyz)
  X03 = c(X03, xyz[1])
  Y03 = c(Y03, xyz[2])
  Z03 = c(Z03, xyz[3])
}

par(pty="s", mar=c(4,0,2.4,0))
plot(X03, Y03, pch=".", asp=1, xlab = "x", ylab="y", ylim=c(0, 0.3), main = paste("gamma = ", gamma, sep=""), xlim=c(0.2, 0.55))
points( (mu-1)/mu,0, col="orange",pch=19)
points( 1/beta, 1-1/mu-1/beta, col="green",pch=19)
points( (1-1/mu+1/beta-1/gamma)/2, 1/gamma, col="blue",pch=19)
```

gamma=7.3
```{r}
mu=2.1
beta=3.36

gamma=7.3

xyz = c(0.1, 0.02, 0.03)
X1 = xyz[1]
Y1 = xyz[2]
Z1 = xyz[3]

iterazioni=2e4
for(i in 1:iterazioni){
  xyz=T(xyz)
  X1 = c(X1, xyz[1])
  Y1 = c(Y1, xyz[2])
  Z1 = c(Z1, xyz[3])
}
```

```{r}
par(pty="s", mar=c(4,0,2.4,0))
plot(X1, Y1, pch=".", asp=1, ylim=c(0,0.3), xlab = "x", ylab="y", main = paste("gamma = ", gamma, sep=""))
points( (mu-1)/mu,0, col="orange",pch=19)
points( 1/beta, 1-1/mu-1/beta, col="green",pch=19)
points( (1-1/mu+1/beta-1/gamma)/2, 1/gamma, col="blue",pch=19)
```

gamma=7.46
```{r}
gamma=7.46

xyz = c(0.1, 0.02, 0.03)
X2 = xyz[1]
Y2 = xyz[2]
Z2 = xyz[3]

iterazioni=2e4
for(i in 1:iterazioni){
  xyz=T(xyz)
  X2 = c(X2, xyz[1])
  Y2 = c(Y2, xyz[2])
  Z2 = c(Z2, xyz[3])
}
```

```{r}
par(pty="s", mar=c(4,0,2.4,0))
plot(X2, Y2, pch=".", asp=1, xlab = "x", ylab="y", ylim=c(0, 0.3), main = paste("gamma = ", gamma, sep=""))
points( (mu-1)/mu,0, col="orange",pch=19)
points( 1/beta, 1-1/mu-1/beta, col="green",pch=19)
points( (1-1/mu+1/beta-1/gamma)/2, 1/gamma, col="blue",pch=19)
```

gamma=8.14
```{r}
gamma=8.14

xyz = c(0.1, 0.02, 0.03)
X3 = xyz[1]
Y3 = xyz[2]
Z3 = xyz[3]

iterazioni=2e4
for(i in 1:iterazioni){
  xyz=T(xyz)
  X3 = c(X3, xyz[1])
  Y3 = c(Y3, xyz[2])
  Z3 = c(Z3, xyz[3])
}
```

```{r}
par(pty="s", mar=c(4,0,2.4,0))
plot(X3, Y3, pch=".", asp=1, xlab = "x", ylab="y", ylim=c(0, 0.3), main = paste("gamma = ", gamma, sep=""))
points( (mu-1)/mu,0, col="orange",pch=19)
points( 1/beta, 1-1/mu-1/beta, col="green",pch=19)
points( (1-1/mu+1/beta-1/gamma)/2, 1/gamma, col="blue",pch=19)
```

gamma=9.14
```{r}
gamma=9.14

xyz = c(0.1, 0.02, 0.03)
X4 = xyz[1]
Y4 = xyz[2]
Z4 = xyz[3]

iterazioni=2e4
for(i in 1:iterazioni){
  xyz=T(xyz)
  X4 = c(X4, xyz[1])
  Y4 = c(Y4, xyz[2])
  Z4 = c(Z4, xyz[3])
}
```

```{r}
par(pty="s", mar=c(4,0,2.4,0))
plot(X4, Y4, pch=".", asp=1, xlab = "x", ylab="y", ylim=c(0, 0.3), main = paste("gamma = ", gamma, sep=""))
points( (mu-1)/mu,0, col="orange",pch=19)
points( 1/beta, 1-1/mu-1/beta, col="green",pch=19)
points( (1-1/mu+1/beta-1/gamma)/2, 1/gamma, col="blue",pch=19)
```

```{r}
plot_ly(x=X4, y=Y4, z=Z4, type="scatter3d", mode="markers", color=Z4, marker = list(size = 0.8), )
```

