---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	cache = TRUE,
	fig.align = "center",
	warning = FALSE,
	out.width = "70%",
	tidy = TRUE,
	tidy.opts = list(width.cutoff = 60)
)
library(knitr)
library(plotly)
```

```{r}
find_loc_max = function(series, quanti){
  result=c()
  for (i in 2:(length(series)-1)) {
    if(series[i]>series[i-1] & series[i]>series[i+1]){
      quanti = quanti -1
      result = c(result, series[i])
    }
    if(quanti==0)
      break
  }
  return(result)
}
```

```{r}
T = function(vector){
  x=vector[1]
  y=vector[2]
  z=vector[3]
  temp=c( mu*x*(1-x-y-z),
          beta*y*(x-z),
          gamma*y*z)
  for(i in 1:3){
    if(temp[i]<0)
      temp[i]=0
  }
  if(x+y+z>1)
    temp[1]=0
  return(temp)
}
```

gamma=6.8
```{r}
mu=2.1
beta=3.36

gamma=6.8

xyz = c(0.2, 0.25, 0.05)
X11 = c()

preiterazioni=3e4
for(i in 1:preiterazioni){
  xyz=T(xyz)
}

for(i in 1:150){
  xyz=T(xyz)
  X11 = c(X11, xyz[1])
}

par(mar=c(4,4, 1, 0.5))#, mfrow=c(1,2))
plot(1:length(X11), X11, pch=".", type="l",xlab="Index", ylab=expression(x[n]))
abline(h=find_loc_max(X11,1), col="lightblue", lwd=3)
points(1:length(X11), X11,pch=16)

for(i in 1:(2048-150)){
  xyz=T(xyz)
  X11 = c(X11, xyz[1])
}

par(mar=c(4,4, 1, 0.5))
fft01 = abs(fft(X11, inverse = FALSE))[-1]
plot(1:200,fft01[1:200], type="l", xlab="index", ylab="Magnitude")
# title(main=paste("gamma = ", gamma, sep=""))
```

gamma=7.1
```{r}
mu=2.1
beta=3.36

gamma=7.1

xyz = c(0.2, 0.25, 0.05)
X12 = c()

preiterazioni=3e4
for(i in 1:preiterazioni){
  xyz=T(xyz)
}

for(i in 1:150){
  xyz=T(xyz)
  X12 = c(X12, xyz[1])
}

par(mar=c(4,4, 1, 0.5))
plot(1:length(X12), X12, pch=".", type="l",xlab="Index", ylab=expression(x[n]))
abline(h=find_loc_max(X12, 2), col="lightblue", lwd=3)
# abline(h=X12[39], col="lightblue", lwd=3)
points(1:length(X12), X12,pch=16)
```

```{r}
for(i in 1:(2048-150)){
  xyz=T(xyz)
  X12 = c(X12, xyz[1])
}

par(mar=c(4,4, 1, 0.5))
fft02 = abs(fft(X12, inverse = FALSE))[-1]
plot(1:200,fft02[1:200], type="l", xlab="index", ylab="Magnitude")
```


gamma=7.18
```{r}
mu=2.1
beta=3.36

gamma=7.18

xyz = c(0.2, 0.25, 0.05)
X13 = c()

preiterazioni=3e4
for(i in 1:preiterazioni){
  xyz=T(xyz)
}

for(i in 1:150){
  xyz=T(xyz)
  X13 = c(X13, xyz[1])
}

par(mar=c(4,4, 1, 0.5))
plot(1:length(X13), X13, pch=".", type="l",xlab="Index", ylab=expression(x[n]))
abline(h=find_loc_max(X13, 4), col="lightblue", lwd=3)
points(1:length(X13), X13,pch=16)
```

```{r}
for(i in 1:(2048-150)){
  xyz=T(xyz)
  X13 = c(X13, xyz[1])
}

par(mar=c(4,4, 1, 0.5))
fft03 = abs(fft(X13, inverse = FALSE))[-1]
plot(1:200,fft03[1:200], type="l", xlab="index", ylab="Magnitude")
```

gamma=7.4
```{r}
mu=2.1
beta=3.36

gamma=7.4
# gamma=8

xyz = c(0.2, 0.25, 0.05)
X14 = c()

preiterazioni=3e4
for(i in 1:preiterazioni){
  xyz=T(xyz)
}

for(i in 1:150){
  xyz=T(xyz)
  X14 = c(X14, xyz[1])
}

par(mar=c(4,4, 1, 0.5))
plot(1:length(X14), X14, pch=".", type="l",xlab="Index", ylab=expression(x[n]))
abline(h=find_loc_max(X14, 9), col="lightblue", lwd=3)
points(1:length(X14), X14,pch=16)
```

```{r}
for(i in 1:(2048-150)){
  xyz=T(xyz)
  X14 = c(X14, xyz[1])
}

par(mar=c(4,4, 1, 0.5))
fft04 = abs(fft(X14, inverse = FALSE))[-1]
plot(1:200,fft04[1:200], type="l", xlab="index", ylab="Magnitude")
```


```{r}
mu=2.1
beta=3.36

gamma_v = seq(6.6, 8, length=200)
df=c()

for(gamma in gamma_v){
  xyz = c(0.2, 0.25, 0.05)
  X15 = c()
  
  preiterazioni=3e3
  for(i in 1:preiterazioni){
    xyz=T(xyz)
  }
  
  iterazioni=1200
  for(i in 1:iterazioni){
    xyz=T(xyz)
    X15 = c(X15, xyz[1])
  }
  
  tt=find_loc_max(X15, iterazioni)
  for(i in tt){
    df = rbind(df, c(gamma, i))
  }
  
  cat(round((gamma-min(gamma_v))/(max(gamma_v)-min(gamma_v))*100,1), " ")
}

par(mar=c(4,4, 1, 0.5))
plot(df[,1], df[,2], pch=".", xlab="gamma", ylab="local maxima")
```

```{r}
mu=2.1
gamma=6.5

beta_v = seq(3.4, 3.8, length=200)
df=c()

for(beta in beta_v){
  xyz = c(0.2, 0.25, 0.05)
  X16 = c()
  
  preiterazioni=3e3
  for(i in 1:preiterazioni){
    xyz=T(xyz)
  }
  
  iterazioni=1200
  for(i in 1:iterazioni){
    xyz=T(xyz)
    X16 = c(X16, xyz[1])
  }
  
  for(i in find_loc_max(X16, 160)){
    df = rbind(df, c(beta, i))
  }
  
  cat(round((beta-min(beta_v))/(max(beta_v)-min(beta_v))*100,1), " ")
}

par(mar=c(4,4, 1, 0.5))
plot(df[,1], df[,2], pch=".", xlab="beta", ylab="local maxima")
```
