---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---


```{r eval=FALSE, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	cache = TRUE,
	fig.align = "center",
	warning = FALSE,
	out.width = "70%",
	tidy = TRUE,
	tidy.opts = list(width.cutoff = 60)
)
```

```{r BASE TOOLS, warning=FALSE}
library(maptools)
library(spatstat)
library(plotly)
library(LaplacesDemon)

rm(list=ls())
# setwd("C:/Users/lofer/Dropbox/POLI/quantitative/paper")

mu = 0.7
beta = 2.5
gamma = 5

T = function(vector){
  x=vector[1]
  y=vector[2]
  z=vector[3]
  temp=c( mu*x*(1-x-y-z),
          beta*y*(x-z),
          gamma*y*z)
  for(i in 1:3){
    if(temp[i]<0)
      temp[i]=0
  }
  return(temp)
}

is.over.carrying.capacity = function(vector){
  x=vector[1]
  y=vector[2]
  z=vector[3]
  if(x+y+z>1)
    return(1)
  return(0)
}

{
N=200
valori.x = (1:N)/N
valori.z = valori.x
}

num_iterazioni=500
quante_simul=57
```


P1:
AS sink 0 < mu < 1, saddle mu > 1

P2:
AS sink 1 < mu < beta/(beta−1), saddle beta/(beta−1) < mu < 3

P3:
AS sink beta/(beta−1) < μ ≤ 2beta(beta−1−sqrt(β(β−2))), 
AS node 2*beta*(beta-1-sqrt(beta*(beta-2))) < mu < beta*gamma/((beta11)*gamma - beta) : 

```{r caso 1}
#p1 = saddle
#P2 = AS sink
beta=3
mu = (1+ beta/(beta-1))/2   #=1.25
gamma=5

fixed.points = data.frame( t(matrix(c(0,0,0, (mu-1)/mu, 0, 0, 1/beta, 1-1/mu-1/beta, 0), nrow = 3)) )
names(fixed.points)=c("x", "y", "z")
fixed.points$gruppo = c(1,2,3)

series=c()
gruppo=c()

set.seed(1222)

for(index in seq(0, 0.5, length=quante_simul)){

  r=min(rexp(n = 1, rate = 2), 1)
  temp=matrix( r*rdirichlet(1, c(1,1,1)), nrow=1)
  gruppo= c(gruppo, index)

    for (n in 1:(num_iterazioni-1)) {
      aggiunta = T(temp[n,])
      if( is.over.carrying.capacity(aggiunta))
        break
      
      temp=rbind( temp, aggiunta)
      gruppo= c(gruppo, index)
    }
  series = rbind(series, temp)
}

out = data.frame( gruppo = gruppo, x = series[,1], y = series[,2], z = series[,3])

p3 <- plot_ly(out, x= ~x, y = ~y, z = ~z, split = ~gruppo, type = 'scatter3d', mode = 'lines', line = list(width = 4)) %>% 
  add_trace(data = fixed.points[1,], x = ~x, y = ~y, z = ~z,  mode = "markers", type = "scatter3d", marker = list(size = 5)) %>% 
  add_trace(data = fixed.points[2,], x = ~x, y = ~y, z = ~z,  mode = "markers", type = "scatter3d", marker = list(size = 5)) %>% 
  add_trace(data = fixed.points[3,], x = ~x, y = ~y, z = ~z,  mode = "markers", type = "scatter3d", marker = list(size = 5))
p3
```


```{r caso 1.1}
#p1 = saddle
#P2 = AS sink
beta=3
mu = (1+ beta/(beta-1))/2   #=1.25
gamma=5

fixed.points = data.frame( t(matrix(c(0,0,0, (mu-1)/mu, 0, 0, 1/beta, 1-1/mu-1/beta, 0), nrow = 3)) )
names(fixed.points)=c("x", "y", "z")
fixed.points$gruppo = c(1,2,3)

series=c()
gruppo=c()

set.seed(1222)

for(index in seq(0, 0.5, length=quante_simul)){

  temp=matrix( abs(mvrnorm(n = 1, mu = c(0,0,0), Sigma = diag(3)*0.1 ) ), nrow=1)
  gruppo= c(gruppo, index)

    for (n in 1:(num_iterazioni-1)) {
      aggiunta = T(temp[n,])
      if( is.over.carrying.capacity(aggiunta))
        break
      
      temp=rbind( temp, aggiunta)
      gruppo= c(gruppo, index)
    }
  series = rbind(series, temp)
}

out = data.frame( gruppo = gruppo, x = series[,1], y = series[,2], z = series[,3])

p3 <- plot_ly(out, x= ~x, y = ~y, z = ~z, split = ~gruppo, type = 'scatter3d', mode = 'lines', line = list(width = 4)) %>% 
  add_trace(data = fixed.points[1,], x = ~x, y = ~y, z = ~z,  mode = "markers", type = "scatter3d", marker = list(size = 5)) %>% 
  add_trace(data = fixed.points[2,], x = ~x, y = ~y, z = ~z,  mode = "markers", type = "scatter3d", marker = list(size = 5)) %>% 
  add_trace(data = fixed.points[3,], x = ~x, y = ~y, z = ~z,  mode = "markers", type = "scatter3d", marker = list(size = 5))
p3
```


```{r}
#p1 = saddle
#P2 = saddle
#p3 = AS sink
beta=3
mu = ( beta/(beta-1) + 2*beta*(beta-1-sqrt(beta*(beta-2))) )/2   #=1.25
gamma=5

fixed.points = data.frame( t(matrix(c(0,0,0, (mu-1)/mu, 0, 0, 1/beta, 1-1/mu-1/beta, 0), nrow = 3)) )
names(fixed.points)=c("x", "y", "z")
fixed.points$gruppo = c(1,2,3)

# quante_simul=17

series=c()
gruppo=c()

set.seed(1222)

for(index in seq(0, 0.5, length=quante_simul)){
  
  temp=matrix( abs(mvrnorm(n = 1, mu = c(0,0,0), Sigma = diag(3)*0.1 ) ), nrow=1)

  gruppo= c(gruppo, index)

    for (n in 1:(num_iterazioni-1)) {
      aggiunta = T(temp[n,])
      if( is.over.carrying.capacity(aggiunta))
        break
      
      temp=rbind( temp, aggiunta)
      gruppo= c(gruppo, index)
    }
  series = rbind(series, temp)
}

out = data.frame( gruppo = gruppo, x = series[,1], y = series[,2], z = series[,3])

p3 <- plot_ly(out, x= ~x, y = ~y, z = ~z, split = ~gruppo, type = 'scatter3d', mode = 'lines', line = list(width = 4)) %>% 
  add_trace(data = fixed.points[1,], x = ~x, y = ~y, z = ~z,  mode = "markers", type = "scatter3d", marker = list(size = 5)) %>% 
  add_trace(data = fixed.points[2,], x = ~x, y = ~y, z = ~z,  mode = "markers", type = "scatter3d", marker = list(size = 5)) %>% 
  add_trace(data = fixed.points[3,], x = ~x, y = ~y, z = ~z,  mode = "markers", type = "scatter3d", marker = list(size = 5))
p3
```

```{r}
#p1 = saddle
#P2 = saddle
#p3 = AS node
beta=3
mu = ( 2*beta*(beta-1-sqrt(beta*(beta-2))) + beta*gamma/((beta-1)*gamma - beta) )/2  #=1.875276
gamma=5

fixed.points = data.frame( t(matrix(c(0,0,0, (mu-1)/mu, 0, 0, 1/beta, 1-1/mu-1/beta, 0), nrow = 3)) )
names(fixed.points)=c("x", "y", "z")
fixed.points$gruppo = c(1,2,3)

# quante_simul=57

series=c()
gruppo=c()

set.seed(1222)

for(index in seq(0, 0.5, length=quante_simul)){

  r=min(rexp(n = 1, rate = 1/0.7), 1)
  temp=matrix( r*rdirichlet(1, c(1,1,1)), nrow=1)
  gruppo= c(gruppo, index)

    for (n in 1:(num_iterazioni-1)) {
      aggiunta = T(temp[n,])
      if( is.over.carrying.capacity(aggiunta))
        break
      
      temp=rbind( temp, aggiunta)
      gruppo= c(gruppo, index)
    }
  series = rbind(series, temp)
}

out = data.frame( gruppo = gruppo, x = series[,1], y = series[,2], z = series[,3])

p3 <- plot_ly(out, x= ~x, y = ~y, z = ~z, split = ~gruppo, type = 'scatter3d', mode = 'lines', line = list(width = 4)) %>% 
  add_trace(data = fixed.points[1,], x = ~x, y = ~y, z = ~z,  mode = "markers", type = "scatter3d", marker = list(size = 5)) %>% 
  add_trace(data = fixed.points[2,], x = ~x, y = ~y, z = ~z,  mode = "markers", type = "scatter3d", marker = list(size = 5)) %>% 
  add_trace(data = fixed.points[3,], x = ~x, y = ~y, z = ~z,  mode = "markers", type = "scatter3d", marker = list(size = 5))
p3
```

T