---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	cache = TRUE,
	fig.align = "center",
	warning = FALSE,
	out.width = "70%",
	tidy = TRUE,
	tidy.opts = list(width.cutoff = 60)
)
library(knitr)
library(plotly)
```

```{r}
T = function(vector){
  x=vector[1]
  y=vector[2]
  z=vector[3]
  temp=c( mu*x*(1-x-y-z),
          beta*y*(x-z),
          gamma*y*z)
  for(i in 1:3){
    if(temp[i]<0)
      temp[i]=0
  }
  if(x+y+z>1)
    temp[1]=0
  return(temp)
}
```

```{r}
mu=0.9
beta=3.36

gamma=5.3

set.seed(1234)
xyz = rbind(c(0.1, 0.02, 0.03),c(0.06, 0.04, 0.05),c(0.03, 0.02, 0.06),c(0.07, 0.03, 0.08),c(0.01, 0.03, 0.1), c(0.08, 0.02, 0.04))

X71 = xyz[,1]
Y71 = xyz[,2]
Z71 = xyz[,3]

iterazioni=2e1
M=(dim(xyz)[1])
for(i in 1:iterazioni){
  for (j in 1:M) {
    xyz[j,] = T(xyz[j,])
  }
  X71 = rbind(X71, xyz[,1])
  Y71 = rbind(Y71, xyz[,2])
  Z71 = rbind(Z71, xyz[,3])
}


```

```{r}
par(pty="s", mfrow=c(1,3),mar=c(0,5,0,0.5))

plot(X71[,1], Y71[,1], xlab = substitute(paste(bold('x'))), ylab=substitute(paste(bold('y'))),type="l", ylim=c(0, max(Y71)), xlim=c(0, max(X71)), pch=".")
for (j in 2:M)
  lines(X71[,j], Y71[,j], type="l", pch=".")
points( 0,0, col="red",pch=19, cex=1.5)
points( (mu-1)/mu,0, col="orange",pch=19, cex=1.5)
points( 1/beta, 1-1/mu-1/beta, col="green",pch=19, cex=1.5)
points( (1-1/mu+1/beta-1/gamma)/2, 1/gamma, col="blue",pch=19, cex=1.5)

plot(X71[,1], Z71[,1], xlab = substitute(paste(bold('x'))), ylab=substitute(paste(bold('z'))),type="l", ylim=c(0, max(Z71)), xlim=c(0, max(X71)), pch=".")
for (j in 2:M)
  lines(X71[,j], Z71[,j], type="l", pch=".")
points( 0,0, col="red",pch=19, cex=1.5)
points( (mu-1)/mu,0, col="orange",pch=19, cex=1.5)
points( 1/beta, 0, col="green",pch=19, cex=1.5)
points( (1-1/mu+1/beta-1/gamma)/2, (1-1/mu-1/beta-1/gamma)/2, col="blue",pch=19, cex=1.5)

plot(Y71[,1], Z71[,1], xlab = substitute(paste(bold('y'))), ylab=substitute(paste(bold('z'))),type="l", ylim=c(0, max(Z71)), xlim=c(0, max(Y71)), pch=".")
for (j in 2:M)
  lines(Y71[,j], Z71[,j],type="l", pch=".")
points( 0,0, col="red",pch=19, cex=1.5)
# points( 0,0, col="orange",pch=19, cex=1.5)
points( 1-1/mu-1/beta, 0, col="green",pch=19, cex=1.5)
points( 1/gamma, (1-1/mu-1/beta-1/gamma)/2, col="blue",pch=19, cex=1.5)
```





```{r}
beta=3.36

mu = mean(c(1, beta/(beta-1)))

gamma=5.3

xyz = rbind(c(0.1, 0.02, 0.03),c(0.06, 0.04, 0.05),c(0.03, 0.02, 0.06),c(0.07, 0.03, 0.08),c(0.01, 0.03, 0.1), c(0.08, 0.02, 0.04))

X72 = xyz[,1]
Y72 = xyz[,2]
Z72 = xyz[,3]

iterazioni=2e1
M=(dim(xyz)[1])
for(i in 1:iterazioni){
  for (j in 1:M) {
    xyz[j,] = T(xyz[j,])
  }
  X72 = rbind(X72, xyz[,1])
  Y72 = rbind(Y72, xyz[,2])
  Z72 = rbind(Z72, xyz[,3])
}


```

```{r}
par(pty="s", mfrow=c(1,3),mar=c(0,5,0,0.5))

plot(X72[,1], Y72[,1], xlab = substitute(paste(bold('x'))), ylab=substitute(paste(bold('y'))),type="l", ylim=c(0, max(Y72)), xlim=c(0, max(X72)), pch=".")
for (j in 2:M)
  lines(X72[,j], Y72[,j], type="l", pch=".")
points( 0,0, col="red",pch=19, cex=1.5)
points( (mu-1)/mu,0, col="orange",pch=19, cex=1.5)
points( 1/beta, 1-1/mu-1/beta, col="green",pch=19, cex=1.5)
points( (1-1/mu+1/beta-1/gamma)/2, 1/gamma, col="blue",pch=19, cex=1.5)

plot(X72[,1], Z72[,1], xlab = substitute(paste(bold('x'))), ylab=substitute(paste(bold('z'))),type="l", ylim=c(0, max(Z72)), xlim=c(0, max(X72)), pch=".")
for (j in 2:M)
  lines(X72[,j], Z72[,j], type="l", pch=".")
points( 0,0, col="red",pch=19, cex=1.5)
points( (mu-1)/mu,0, col="orange",pch=19, cex=1.5)
points( 1/beta, 0, col="green",pch=19, cex=1.5)
points( (1-1/mu+1/beta-1/gamma)/2, (1-1/mu-1/beta-1/gamma)/2, col="blue",pch=19, cex=1.5)

plot(Y72[,1], Z72[,1], xlab = substitute(paste(bold('y'))), ylab=substitute(paste(bold('z'))),type="l", ylim=c(0, max(Z72)), xlim=c(0, max(Y72)), pch=".")
for (j in 2:M)
  lines(Y72[,j], Z72[,j], type="l", pch=".")
points( 0,0, col="red",pch=19, cex=1.5)
points( 0,0, col="orange",pch=19,cex=1.5)
points( 1-1/mu-1/beta, 0, col="green",pch=19, cex=1.5)
points( 1/gamma, (1-1/mu-1/beta-1/gamma)/2, col="blue",pch=19, cex=1.5)
```


